# -*- coding: utf-8 -*-
"""financeiro - analise de portifolio de investimento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CUD3li8z3MyKIHTrQ7GLc-c_3T3YeK1
"""

# Importa as bibliotecas necessárias
import pandas as pd
from io import StringIO
import numpy as np

# String que contém os dados de retorno
dados_portfolio_str = """
Mes,Retorno_A,Retorno_B,Retorno_C
1,0.015,0.008,0.003
2,-0.020,0.005,0.004
3,0.030,0.010,0.002
4,0.005,0.007,0.005
5,-0.010,0.009,0.003
"""

# Cria o DataFrame
df_portfolio = pd.read_csv(StringIO(dados_portfolio_str))
df_retornos = df_portfolio.drop('Mes', axis=1)

# Cálculo 1: Retornos Médios Anualizados
# Multiplica por 12 para anualizar os retornos mensais simulados
retornos_medios_anualizados = df_retornos.mean() * 12

# Cálculo 2: Matriz de Covariância (Risco)
# Multiplica por 12 para anualizar o risco
matriz_covariancia_anualizada = df_retornos.cov() * 12

print("--- DataFrame de Retornos Criado ---")
print(df_retornos)

print("\n--- Retornos Médios Anualizados ---")
print(retornos_medios_anualizados)

print("\n--- Matriz de Covariância (Risco Anualizado) ---")
print(matriz_covariancia_anualizada)